---
functional:
  - На сайте есть возможность зарегистрироваться
  - Есть возможность авторизоваться через аккаунт в GitHab
  - Есть возможность создать игру
  - Есть возможность выбрать уровень игры
  - Есть возможность написать свой код
  - Есть возможность протестировать свой код
  - Сайт возвращает результаты игры
  - Есть возможность взаимодействовать с чатом
  - Есть возможность выбирать соперника
  - Есть возможность создать новую задачу
  - Есть возможность создать клан
  - Есть возможность создать турнир
  - Есть возможность приглашать пользователей в турнир
  - Есть возможность принимать приглашение на участие в турнире
  - Есть возможность общаться в чате
  - Есть возможность выбрать нужный язык программирования
non-functional:
  - Сайт имеет интуитивно понятную для пользователя структуру
  - Сайт поддерживает адаптивную верстку
  - Сайт использует защищенный https протокол
  - Сайт совместим с последними версиями браузеров
  - Сайт способен обрабатывать 1000 одновременных пользователей
implicit:
  - Сайт предоставляет защиту от читерства
  - Сайт поддерживает различные языки
