---
functional:
  - На сайте есть возможность зарегистрироваться
  - Есть возможность выбрать способ входа в аккаунт
  - Есть возможность создать игру
  - Есть возможность написать свой код
  - Есть возможность протестировать свой код
  - Сайт возвращает результаты игры
  - Есть возможность взаимодействовать с чатом
  - Есть возможность выбирать соперника
non-functional:
  - Сайт имеет интуитивно понятную для пользователя структуру
  - Сайт поддерживает адаптивную верстку
  - Сайт использует защищенный https протокол
  - Сайт совместим с последними версиями браузеров
  - Сайт способен обрабатывать 1000 одновременных пользователей
implicit:
  - Сайт предоставляет защиту от читерства
  - На сайте есть возможность скрыть свой код или код соперника
  - Сайт поддерживает различные языки
